version: "3.4"
services:

  backend:
    restart: always
    container_name: backend
    #command : bash -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./addressbook/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      vpcbr:
        ipv4_address: 172.28.1.3
   


  frontend:
    restart: always
    #command : npm start --host 0.0.0.0
    container_name: frontend
    build:
      context: ./addressbook-frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    #network_mode : host
    networks:
      vpcbr:
        ipv4_address: 172.28.1.2
    
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         gateway: 172.28.1.1